### ISSUE TITLE
New release PyPI

### ISSUE THREAD

**Issue by ThomasTNO** [lschoe/mpyc#19]
For when is the new release for PyPI planned?

**Comment by lschoe** [comment]
Indeed, it's about time to package the changes since v0.6. A safe answer is by the end of October, in about two weeks.

**Comment by lschoe** [comment]
Scary, just made the deadline for releasing MPyC v0.7
![MPyC_Logo|20%](https://user-images.githubusercontent.com/25797349/97786235-9994fb00-1baa-11eb-869a-852b486be5f9.png)

**Comment by ThomasTNO** [comment]
Fantastic! Great achievement :)
