### ISSUE TITLE
Coefficients used in reverse order

### ISSUE THREAD

**Issue by markulf** [lschoe/mpyc#2]
https://github.com/lschoe/mpyc/blob/e04f5b6d430a1ee32d0f1bdc689569166beb566f/mpyc/thresha.py#L32

```
# polynomial f(x) = s[h] + c[0] x + c[1] x^2 + ... + c[d-1] x^d
        for i in range(n):
            y = 0
            for c_k in c:
                y += c_k
                y *= i + 1
```

Would the code not compute `f(x) = s[h] + c[0] x^d + ... c[d-2] x^2 + c[d-1] x^1`

Uncertain whether this is a real issue, and if it is what the best fix would be.

**Comment by lschoe** [comment]
Thanks for your comment! 
It was best to fix the comment line, as you suggested using c in reverse.
