### ISSUE TITLE
How to understand the privacy in demo `unaimous.py`?

### ISSUE THREAD

**Issue by allensll** [lschoe/mpyc#20]
Hi,

The core code for unaimous.py is as follows:
```
mpc.run(mpc.start())

votes = mpc.input(secbit(vote), senders=voters)

result = mpc.run(mpc.output(mpc.all(votes), receivers=voters))

mpc.run(mpc.shutdown())
```
I tried a two-party instance. For one party, after executing 
`result = mpc.run(mpc.output(mpc.all(votes), receivers=voters))`,
I find that this party could see all votes from the variable `vates`, so how to understand the privacy of this demo?

**Comment by lschoe** [comment]
Well, the number of parties m is supposed to be odd. Did you remove the following lines to be able to run the demo with m=2?
```
if m%2 == 0:
    print('Odd number of parties required.')
    sys.exit()
```

If you run unanimous.py with m = 2t+1 parties, then you have t+1 voters. The remaining t parties serve as 'trusted' parties which are assumed not to collude with any of the voters.

For example, with m=3 parties you have t+1=2 voters (P0=Alice and P1=Bob) and t=1 'trusted third' party P2. The extra party P2 ensures that we have an honest majority. The privacy is that Alice cannot see Bob's vote, Bob cannot see Alice's vote, and P2 cannot see anything. The output whether Alice and Bob both voted 'yes' is only available for Alice and Bob.

For m=2t+1 parties the output is whether all t+1 voters voted 'yes' (unanimous agreement). The voters learn no other information than implied by this output, unless all t+1 of them collude, but then they would know it all anyway. The t 'trusted' parties learn nothing at all, even if all t of them collude.

**Comment by allensll** [comment]
Thanks, @lschoe.

So, does it means that this scheme cannot be applied to the two-party example？

Another question, can I apply the MPyC to solve the Millionaire's Problem？

**Comment by lschoe** [comment]
Hi @allensll. 

So with MPyC we need an honest majority. If you run it with two parties, the two parties are both assumed to be honest. Technically, a Shamir secret sharing with threshold t=0 is then used, which means that both parties see all the values in the clear.
To tolerate one corrupt party (t=1) we need to take m =2t+1 = 3 at least. 

Hence, two-party computation with a dishonest majority is not supported by MPyC (or any other framework assuming honest majority). Two-party computation with dishonest majority requires much heavier crypto than Shamir secret sharing, e.g., oblivious transfer relying on many public key operations.

However, the setting of the demo [mpyc/demos/unanimous.py](https://github.com/lschoe/mpyc/blob/master/demos/unanimous.py) offers a reasonable alternative, which you can also use for the millionaires problem. Together with a third party, Alice and Bob run the MPyC program comparing their inputs. The third party can be viewed as the server that provides the 'millionaires service' to any two users who like to run a comparison.

The server does not learn anything, and the assumption that the server does not collude with any of the users is very reasonable in many cases. The MPC protocols will be relatively lightweight (no public key operations needed). And **much** better than fully trusting the server and letting Alice and Bob send all their data to the server which will then compute the result for them--which is what one gets without using MPC.

**Comment by allensll** [comment]
Thanks for your reply, @lschoe.
