### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by NilsHendrikLukas** [lschoe/mpyc#3]
Does MPyC have options of using multiple threads? I couldn't find it in the documentation.

Thanks!

**Comment by lschoe** [comment]
MPyC currently uses one global runtime which will break when used from multiple threads. However, the asyncio event loop is used to the max running often hundreds to thousands of tasks concurrently, to make sure that the secure computation proceeds as quickly as possible. In particular, idle time waiting for messages from the other parties is minimized.

Do you have a specific use case in mind?
