### ISSUE TITLE
Number of local Parties

### ISSUE THREAD

**Issue by martino1988** [lschoe/mpyc#32]
Is it possible to "hardcode" the number of local parties, e.g. 3, ($ mpyc_script.py -M3) so that i can run a function of that script (mpyc_script.make_shares(arguments)) without having to run the complete script (os.system("python mpyc_script.py -M3"))? 

thx

**Comment by lschoe** [comment]
Well, a script is supposed to be run by a single party. Using the -M3 option will spawn two additional processes running the scripts for parties 1 and 2 (party 0 is covered by the original process running the script).

What would you like to do this way? Have a quick look at the shares of all the parties, maybe for debugging?

**Comment by martino1988** [comment]
i want to compute all the shares of all parties and display them on a flask web-app. But i´ll guess i will work with a workaraound like:

every mpyc-python file has only one method and manage arguments with sys / sys.argv

PARTIES = 3

def main(year, month):
  os.system("python mpyc_script.py -M"+str(PARTIES)+ " " + str(year) + " " + str(month))

**Comment by lschoe** [comment]
Right, having the shares of all parties in one script would not be really secure;)
