### ISSUE TITLE
mpc.convert() from mpc.SecFld() has issues with negative numbers

### ISSUE THREAD

**Issue by b-kamphorst** [lschoe/mpyc#8]
It appears that the conversion from (signed) SecFld objects to other objects yields incorrect results when the shared secret has a negative value.

```
from mpyc.runtime import mpc

async def main():
    await mpc.start()
    secint = mpc.SecInt()
    secfld = mpc.SecFld(min_order=2**10, signed=True)

    a = secint(3)
    a = mpc.input(a, 0)
    print(await mpc.output(a))
    b = mpc.convert(a, secfld)
    print(await mpc.output(b))
    c = mpc.convert(b, secint)
    print(await mpc.output(c))

    await mpc.shutdown()

if __name__ == "__main__":
    mpc.run(main())
```

Result:

```
2020-03-03 16:55:50,690 Install package gmpy2 for better performance.
2020-03-03 16:55:50,691 Start MPyC runtime v0.6
-3
-3
1028
2020-03-03 16:55:50,700 Stop MPyC runtime -- elapsed time: 0:00:00.009001
```

Of course, we'd expect the result to be -3. Help would be appreciated!

**Comment by lschoe** [comment]
Yeah, also a good point. This is not so easy to fix, but certainly possible. 

Near the end of _convert() in runtime.py there is this call "self._mod(ttype(x[i]), stype.field.modulus)" (line 490). This results in an unsigned value between 0 and the modulus.

To fix this issue, function _mod() needs to be extended to output a signed modulo value in the range -modulus/2 to modulus/2. That can be done at the expense of an extra comparison.

As a workaround you can add this comparison with modulus/2 in your application code. Do you want to try that?

**Comment by b-kamphorst** [comment]
Thank you for the quick response(s). I've been playing around and came to the following piece of code (to be inserted directly after line 490):

```
if ttype.field.is_signed:
    is_neg = x[i] > stype.field.modulus >> 1
    x[i] = x[i] + is_neg * (ttype.field.modulus - stype.field.modulus)
```

This seems to work well, although there should probably be some additional checks here. Perhaps something similar to

```
if stype.field.is_signed and ttype.field.is_signed:
    ...
```
?

**Comment by b-kamphorst** [comment]
Also, I know that you implemented a vectorized version of the secure `>` operation. This might be faster than performing one such operation per element of `x`, although that might already be taken care of by the asynchronous programming?

**Comment by lschoe** [comment]
Indeed, inserting a code fragment like you describe will probably do the job. You can make a pull request for it if you like?

The vectorized comparison is currently only used in the bnnmnist demo, but once that's moved to the runtime it's certainly beneficial to use it here as well.

**Comment by b-kamphorst** [comment]
Hi lschoe,

I noticed that you've been quite busy lately with various improvements. One of them is the __slots__ magic in Runtime, thereby preventing me from overwriting the mpc._convert() function by my temporary fix ;-) (or at least I don't know how to do that). As such this seems to be a perfect time for asking you if you could merge my pull request #10 into the current version of MPyC? If not, what do you need from my side in order to fix this issue?

Best regards and keep up the good work!

**Comment by lschoe** [comment]
OK, I've now merged your fix. Thanks again!
Implementation of function mpc.convert() is still quite limited so will need some further improvements later on. 
I'll also reconsider the use of __slots__ for the Runtime, probably better to drop this indeed.
