### ISSUE TITLE
Conversion from mpc.SecFld() to mpc.SecFxp() incorrectly handles "fractional bits".

### ISSUE THREAD

**Issue by b-kamphorst** [lschoe/mpyc#9]
It seems that conversion from mpc.SecFld() to mpc.SecFxp() has some issues with fractional bits. In particular, the following code produces unexpected results:

```
from mpyc.runtime import mpc

async def main():
    await mpc.start()
    secfxp = mpc.SecFxp()
    secfld = mpc.SecFld(min_order=2**10, signed=True)

    a = secfxp(3)
    a = mpc.input(a, 0)
    print(await mpc.output(a))
    b = mpc.convert(a, secfld)
    print(await mpc.output(b))
    c = mpc.convert(b, secfxp)
    print(await mpc.output(c))

    await mpc.shutdown()

if __name__ == "__main__":
    mpc.run(main())
```
Result:
```
2020-03-03 17:01:02,303 Install package gmpy2 for better performance.
2020-03-03 17:01:02,305 Start MPyC runtime v0.6
3.0
3
196608.0
2020-03-03 17:01:02,320 Stop MPyC runtime -- elapsed time: 0:00:00.014997
```
Noting that, by default, SecFxp assumes 16 fractional bits, the fact that 3 * 2 ** 16 = 196608 suggests that there is some issue in handling the fractional bits. I've not yet had the time to look into this myself, but I can imagine that this issue is relatively easy to fix?

**Comment by lschoe** [comment]
Good point! And your guess makes sense too. I have made a small change based on that.

Can you see if the fix in the branch "fix-conversion-fld-to-fxp" works for you to get rid of the problem? It's only about changing one "if" into an "elif" -- you can also do that directly on your local copy if you like.

**Comment by b-kamphorst** [comment]
Works like a charm! My limited testing revealed no undesired side-effects, so I would suggest to include this fix in the new release.

**Comment by lschoe** [comment]
OK, thanks. Will move this change to the master branch then.

**Comment by b-kamphorst** [comment]
Hi lschoe,

It appears that this change was not moved to the master branch. I did not note that while I used my temporary fix ;-) Could you correct this?

Thank you!

**Comment by lschoe** [comment]
Looks like the change is on the master branch, but not on the fix-conversion-fld-to-fxp branch.

**Comment by b-kamphorst** [comment]
Ah I see now. The change is on the conversion-fld-to-fxp branch branch but not on master. Merging those branches (or equivalently accepting request #14) will solve the issue.
